routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'Front\HomeController@index');
Route::get('test', 'Front\HomeController@resize');
Route::get('image/{path}', function ($path) {
    return $path;
});
Route::get('/s/{code}', 'Front\ProductController@getLink');
Route::get('/home', 'Front\HomeController@index')->name('home');
Route::post('/forgot', 'Api\ForgotPasswordController@index')->name('forgot');
Route::post('/updatePassword', 'Api\ForgotPasswordController@updatePassword')->name('updatePassword');
Route::get('p/{slug}-{id}', 'Front\PageController@view')
    ->where('slug', '.*?')
    ->where('id', '\d+');
Route::get('a/{slug}-{id}', 'Front\PageController@viewAfl')
    ->where('slug', '.*?')
    ->where('id', '\d+');
Route::get('f/{code}', 'Front\PageController@getLink');
Route::get('{slug}-{id}', 'Front\ProductController@detail')
    ->where('slug', '.*?')
    ->where('id', '\d+');

Route::get('/filter', 'Front\ProductController@filter');
Route::get('/category/{slug}', 'Front\ProductController@category');
Route::post('/cart/add', 'Front\CartController@add');
Route::post('/cart/update', 'Front\CartController@update');
Route::get('/cart/checkout', 'Front\CartController@checkout')->name('checkout');
Route::post('/cart/remove', 'Front\CartController@remove');
Route::post('/cart/order', 'Front\CartController@order')->name('order');
Route::get('/order/success', 'Front\CartController@success')->name('order.success');
Route::get('/thong-tin-tai-khoan', 'Front\UserController@me')->name('me');
Route::patch('/me/update', 'Front\UserController@update')->name('me.update');

Route::get('/admin', 'Admin\DashboardController@index');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/filemanager/upload', '\Unisharp\Laravelfilemanager\Controllers\UploadController@upload');
});
Route::group(['middleware' => 'is.admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::get('categories/trash', 'Admin\CategoryController@listTrash')->name('categories.trash.list');
    Route::get('categories/rolback/{id}', 'Admin\CategoryController@rolback')->name('categories.rolback');
    Route::get('categories/trash/{id}', 'Admin\CategoryController@trash')->name('categories.trash.delete');
    Route::resource('categories', 'Admin\CategoryController');
    Route::get('articles/trash', 'Admin\ArticleController@listTrash')->name('articles.trash.list');
    Route::get('articles/rolback/{id}', 'Admin\ArticleController@rolback')->name('articles.rolback');
    Route::get('articles/trash/{id}', 'Admin\ArticleController@trash')->name('articles.trash.delete');
    Route::resource('articles', 'Admin\ArticleController');
    Route::get('users/trash', 'Admin\UserController@trash')->name('users.trash');
    Route::get('users/trash/{id}', 'Admin\UserController@trash_destroy')->name('users.trash.delete');
    Route::get('users/me', 'Admin\UserController@me')->name('users.me');
    Route::resource('users', 'Admin\UserController');
    Route::resource('menus', 'Admin\MenuController');
    Route::post('menus/order', 'Admin\MenuController@order')->name('menus.order');
    Route::post('menus/actions', 'Admin\MenuController@actions')->name('menus.actions');
    Route::get('orders/invoice/{order_id}', 'Admin\OrderController@invoice')->name('orders.invoice');
    Route::resource('orders', 'Admin\OrderController');
    Route::post('/ajax/upload', 'Admin\AjaxController@upload');
    Route::resource('settings', 'Admin\SettingController');
    Route::resource('contacts', 'Admin\ContactController');
    Route::get('pages/trash', 'Admin\PageController@listTrash')->name('pages.trash.list');
    Route::get('pages/rolback/{id}', 'Admin\PageController@rolback')->name('pages.rolback');
    Route::get('pages/trash/{id}', 'Admin\PageController@trash')->name('pages.trash.delete');
    Route::resource('pages', 'Admin\PageController');
    Route::get('affs/trash', 'Admin\AffController@listTrash')->name('affs.trash.list');
    Route::get('affs/rolback/{id}', 'Admin\AffController@rolback')->name('affs.rolback');
    Route::get('affs/trash/{id}', 'Admin\AffController@trash')->name('affs.trash.delete');
    Route::resource('affs', 'Admin\AffController');
    Route::resource('widgets', 'Admin\WidgetController');
    Route::post('widgets/actions', 'Admin\WidgetController@actions')->name('widgets.actions');
    Route::resource('makers', 'Admin\MakerController');
    Route::post('makers/actions', 'Admin\MakerController@actions')->name('makers.actions');
});

resources/views/admin/page/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 1200.88px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add New</h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'Pages' =>route('admin.pages.index'),
                    'Add New',
                    ]])
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <form method="POST" action="{{ route('admin.pages.store') }}" class="form-horizontal" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-9">
                    <div class="card">
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="title" class="col-sm-2">Title</label>
                                <div class="col-sm-10">
                                    <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" class="form-control">

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        {{ $message }}
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="description" class="col-sm-2">Description</label>
                                <div class="col-sm-10">
                                    <textarea name="description" rows="5" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="content" class="col-sm-2">Content</label>
                                <div class="col-sm-10">
                                    <textarea id="my-editor" name="content" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="meta_keyword" class="col-sm-2">Meta Keyword</label>
                                <div class="col-sm-10">
                                    <input name="meta_keyword" class="form-control">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="meta_description" class="col-sm-2">Meta Description</label>
                                <div class="col-sm-10">
                                    <textarea name="meta_description" rows="5" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-3">
                    <div class="card">
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="status" class="col-sm-3">Status</label>
                                <div class="col-sm-9">
                                    <select name="status" class="form-control">
                                        <option value="{{ config('global.status.active') }}">Active </option>
                                        <option value="{{ config('global.status.inactive') }}">InActive</option>
                                    </select>
                                </div>
                            </div>



                            <div class="form-group row">
                                <label for="image" class="col-sm-3">Image</label>
                                <div class="col-sm-9">
                                    <div class="upload-thumb">
                                        <div class="image image-thumbnail">
                                            <a data-preview="thumb" class="change-upload select-image">
                                                <img src="{{ asset('images/image_default.png') }}" width="200">
                                                <span class="btn btn-default btn-sm">Select image</span>

                                            </a>
                                            <span class="image"></span>
                                            <span class="delete"></span>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>

                    </div>
                </div>
            </div>
        </form>
    </section>
</div>
@endsection

@section('script')
<script src="{{ asset("vendor/laravel-filemanager/js/lfm.js") }}"></script>
<script src={{ asset('js/upload.js') }}></script>
@stop

resources/views/admin/page/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Pages <a href="{{ route('admin.pages.create') }}?" class="btn btn-primary btn-sm">Add New</a></h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'Page',
                    ]])
                </div>
                <div class="col-sm-12">
                    @include('admin.includes.alert')
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body pl-0 pr-0">
                        <div id="pages">
                            <div class="row row-option">
                                <div class="col-sm-12 col-md-6">

                                    <form class="form-inline" method="GET" action="{{ route('admin.pages.index') }}?limit=?">
                                        <div class="form-group">
                                            <span>Show</span>
                                            <select name="limit" class="form-control mx-sm-2" onchange="this.form.submit()">
                                                <option value="5" {{ $limit==5?"selected":"" }}>5</option>
                                                <option value="10" {{ $limit==10?"selected":"" }}>10</option>
                                                <option value="25" {{ $limit==25?"selected":"" }}>25</option>
                                                <option value="50" {{ $limit==50?"selected":"" }}>50</option>
                                                <option value="100" {{ $limit==100?"selected":"" }}>100</option>
                                            </select>
                                            <span>entries</span>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <form class="float-right">
                                        <div class="input-group input-group-sm pr-3">
                                            <input type="text" class="form-control" name="search" value="{{ !empty($_GET['search'])?$_GET['search']:"" }}" placeholder="Search keywords">
                                            <div class="input-group-append">
                                                <button class="btn btn-primary">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="table-responsive">
                                        <table class="table table-hover table-striped">
                                            <thead>
                                                <tr role="row">
                                                    <th>Image</th>
                                                    <th>Title</th>
                                                    <th>Link</th>
                                                    <th>Status</th>
                                                    <th>Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($pages as $page)
                                                <tr role="row" class="odd">
                                                    <td width=50>
                                                        @if($page->image)
                                                        <img width="50" src="{{ $page->image }}">
                                                        @else
                                                        <img width="50" src="{{ asset('images/image_default.png') }}">
                                                        @endif
                                                    </td>
                                                    <td tabindex="0" class="sorting_1">{{ $page->title }}</td>
                                                    <td>{{ url('/p/'.$page->slug.'-'.$page->id) }}</td>
                                                    <td>{{ config('global.status.label.'.$page->status) }}</td>
                                                    <td>
                                                        <a class="btn btn-sm btn-success" href="{{ route('admin.pages.edit',$page->id) }}">Update</a>
                                                        <a class="btn btn-sm btn-danger" href="{{ route('admin.pages.trash.delete',$page->id) }}">Trash</a>

                                                    </td>
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-5">
                                    <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing {{($pages->currentpage()-1)*$pages->perpage()+1}} to {{$pages->currentpage()*$pages->perpage()}}
                                        of {{$pages->total()}} entries</div>
                                </div>
                                <div class="col-sm-12 col-md-7">
                                    <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                        {{ $limit?$pages->appends(['limit' => $limit])->links():$pages->links() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
@endsection

resources/views/admin/page/trash.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 1200.88px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Articles <small>(Trash)</small></h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'Articles'=>route('admin.articles.index'),
                    'Trash'
                    ]])
                </div>
                <div class="col-sm-12">
                    @include('admin.includes.alert')
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div id="articles">
                            <div class="row row-option">
                                <div class="col-sm-12 col-md-6">

                                    <form class="form-inline" method="GET" action="{{ route('admin.articles.index') }}?limit=?">
                                        <div class="form-group">
                                            <span>Show</span>
                                            <select name="limit" class="form-control mx-sm-2" onchange="this.form.submit()">
                                                <option value="5" {{ $limit==5?"selected":"" }}>5</option>
                                                <option value="10" {{ $limit==10?"selected":"" }}>10</option>
                                                <option value="25" {{ $limit==25?"selected":"" }}>25</option>
                                                <option value="50" {{ $limit==50?"selected":"" }}>50</option>
                                                <option value="100" {{ $limit==100?"selected":"" }}>100</option>
                                            </select>
                                            <span>entries</span>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <form class="form-inline float-right">
                                        <div class="form-group">
                                            <span>Search</span>
                                            <input type="text" name="search" value="{{ !empty($_GET['search'])?$_GET['search']:"" }}" class="form-control mx-sm-3">
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                                        <thead>
                                            <tr role="row">
                                                <th>Image</th>
                                                <th>Title</th>
                                                <th>Slug</th>
                                                <th>User</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($articles as $article)
                                            <tr role="row" class="odd">
                                                <td width=50>
                                                    @if($article->image)
                                                    <img width="50" src="{{ asset('photos/shares/thumbs/'.$article->image) }}">
                                                    @endif
                                                </td>
                                                <td tabindex="0" class="sorting_1">{{ $article->title }}</td>
                                                <td>{{ $article->slug }}</td>
                                                <td>{{ $article->username }}</td>
                                                <td>
                                                    <a class="btn btn-sm btn-success" href="{{ route('admin.articles.rolback',$article->id) }}">Rolback</a>
                                                    <a class="btn btn-sm btn-danger" href="{{ route('admin.articles.trash.delete',$article->id) }}">Delete</a>

                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-5">
                                    <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing {{($articles->currentpage()-1)*$articles->perpage()+1}} to {{$articles->currentpage()*$articles->perpage()}}
                                        of {{$articles->total()}} entries</div>
                                </div>
                                <div class="col-sm-12 col-md-7">
                                    <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                        {{ $limit?$articles->appends(['limit' => $limit])->links():$articles->links() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
@endsection