routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'Front\HomeController@index');
Route::get('test', 'Front\HomeController@resize');
Route::get('image/{path}', function ($path) {
    return $path;
});
Route::get('/s/{code}', 'Front\ProductController@getLink');
Route::get('/home', 'Front\HomeController@index')->name('home');
Route::post('/forgot', 'Api\ForgotPasswordController@index')->name('forgot');
Route::post('/updatePassword', 'Api\ForgotPasswordController@updatePassword')->name('updatePassword');
Route::get('p/{slug}-{id}', 'Front\PageController@view')
    ->where('slug', '.*?')
    ->where('id', '\d+');
Route::get('a/{slug}-{id}', 'Front\PageController@viewAfl')
    ->where('slug', '.*?')
    ->where('id', '\d+');
Route::get('f/{code}', 'Front\PageController@getLink');
Route::get('{slug}-{id}', 'Front\ProductController@detail')
    ->where('slug', '.*?')
    ->where('id', '\d+');

Route::get('/filter', 'Front\ProductController@filter');
Route::get('/category/{slug}', 'Front\ProductController@category');
Route::post('/cart/add', 'Front\CartController@add');
Route::post('/cart/update', 'Front\CartController@update');
Route::get('/cart/checkout', 'Front\CartController@checkout')->name('checkout');
Route::post('/cart/remove', 'Front\CartController@remove');
Route::post('/cart/order', 'Front\CartController@order')->name('order');
Route::get('/order/success', 'Front\CartController@success')->name('order.success');
Route::get('/thong-tin-tai-khoan', 'Front\UserController@me')->name('me');
Route::patch('/me/update', 'Front\UserController@update')->name('me.update');

Route::get('/admin', 'Admin\DashboardController@index');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/filemanager/upload', '\Unisharp\Laravelfilemanager\Controllers\UploadController@upload');
});
Route::group(['middleware' => 'is.admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::get('categories/trash', 'Admin\CategoryController@listTrash')->name('categories.trash.list');
    Route::get('categories/rolback/{id}', 'Admin\CategoryController@rolback')->name('categories.rolback');
    Route::get('categories/trash/{id}', 'Admin\CategoryController@trash')->name('categories.trash.delete');
    Route::resource('categories', 'Admin\CategoryController');
    Route::get('articles/trash', 'Admin\ArticleController@listTrash')->name('articles.trash.list');
    Route::get('articles/rolback/{id}', 'Admin\ArticleController@rolback')->name('articles.rolback');
    Route::get('articles/trash/{id}', 'Admin\ArticleController@trash')->name('articles.trash.delete');
    Route::resource('articles', 'Admin\ArticleController');
    Route::get('users/trash', 'Admin\UserController@trash')->name('users.trash');
    Route::get('users/trash/{id}', 'Admin\UserController@trash_destroy')->name('users.trash.delete');
    Route::get('users/me', 'Admin\UserController@me')->name('users.me');
    Route::resource('users', 'Admin\UserController');
    Route::resource('menus', 'Admin\MenuController');
    Route::post('menus/order', 'Admin\MenuController@order')->name('menus.order');
    Route::post('menus/actions', 'Admin\MenuController@actions')->name('menus.actions');
    Route::get('orders/invoice/{order_id}', 'Admin\OrderController@invoice')->name('orders.invoice');
    Route::resource('orders', 'Admin\OrderController');
    Route::post('/ajax/upload', 'Admin\AjaxController@upload');
    Route::resource('settings', 'Admin\SettingController');
    Route::resource('contacts', 'Admin\ContactController');
    Route::get('pages/trash', 'Admin\PageController@listTrash')->name('pages.trash.list');
    Route::get('pages/rolback/{id}', 'Admin\PageController@rolback')->name('pages.rolback');
    Route::get('pages/trash/{id}', 'Admin\PageController@trash')->name('pages.trash.delete');
    Route::resource('pages', 'Admin\PageController');
    Route::get('affs/trash', 'Admin\AffController@listTrash')->name('affs.trash.list');
    Route::get('affs/rolback/{id}', 'Admin\AffController@rolback')->name('affs.rolback');
    Route::get('affs/trash/{id}', 'Admin\AffController@trash')->name('affs.trash.delete');
    Route::resource('affs', 'Admin\AffController');
    Route::resource('widgets', 'Admin\WidgetController');
    Route::post('widgets/actions', 'Admin\WidgetController@actions')->name('widgets.actions');
    Route::resource('makers', 'Admin\MakerController');
    Route::post('makers/actions', 'Admin\MakerController@actions')->name('makers.actions');
});

app/Models/Maker.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Maker extends Model
{
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'slug'
    ];
    
    
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at'];
}

app/Http/Controllers/Admin/MakerController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\MakerRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Response;

class makerController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(MakerRepository $makerRepository, UserRepository $userRepository)
    {
        $this->middleware('auth');
        $this->_makerRepository = $makerRepository;
        $this->_userRepository = $userRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $query = $this->_makerRepository->list();
            return view('admin.maker.index', ['makers' => $query]);
        } catch (Exception $e) {
            throw $e;
        }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function listTrash(Request $request)
    {
        try {
            $query = $this->_makerRepository->listTrash();
            return view('admin.maker.trash', ['makers' => $query]);
        } catch (Exception $e) {
            throw $e;
        }
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $parents = $this->_makerRepository->getParent();
            return view('admin.maker.create', ['parents' => $parents]);
        } catch (Exception $e) {
            throw $e;
        }
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->validate($request, [
                'name' => ['required', 'string', 'max:255', 'unique:makers'],
            ]);

            $this->_makerRepository->create($request);
            return redirect()->route('admin.makers.index');
        } catch (Exception $e) {
            throw $e;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        try {
            $result = $this->_makerRepository->find($id);
            return view('admin.maker.update', ['maker' => $result]);
        } catch (Exception $e) {
            throw $e;
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->validate($request, [
                'name' => 'required|string|max:50|unique:makers,name,' . $id,
            ]);
            $this->_makerRepository->update($id, $request);
            return redirect()->route('admin.makers.index');
        } catch (Exception $e) {
            throw $e;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function rolback($id)
    {
        try {

            $result = $this->_makerRepository->rolback($id);

            return redirect()->route('admin.makers.trash.list');
        } catch (Exception $e) {
            throw $e;
        }
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function trash($id)
    {
        try {

            $result = $this->_makerRepository->trash($id);

            return redirect()->route('admin.makers.index');
        } catch (Exception $e) {
            throw $e;
        }
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {

            $result = $this->_makerRepository->delete($id);
            return redirect()->route('admin.makers.index');
        } catch (Exception $e) {
            throw $e;
        }
    }
}

resources/views/admin/maker/_item.blade.php
<tr role="row" class="odd">
    <td>{{ $prefix.' '.$data['title'] }}</td>
    <td>{{ $data['description'] }}</td>
    <td width=200>
        <a class="btn btn-sm btn-success" href="{{ route('admin.categories.edit',$data['id'])}}">Update</a>
        <a class="btn btn-sm btn-danger" href="{{ route('admin.categories.trash.delete',$data['id']) }}">Trash</a>
    </td>
</tr>

resources/views/admin/maker/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 1200.88px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add New</h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'Categories' =>route('admin.categories.index'),
                    'Add New',
                    ]])
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-4">
                <div class="card">
                    <!-- form start -->
                    <form method="POST" action="{{ route('admin.categories.store') }}">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" class="form-control">

                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea name="description" rows="5" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="parent_id">Parent</label>
                                <select name="parent_id" class="form-control">
                                    <option value="">Choose parent</option>
                                    @foreach ($parents as $value)
                                    <option value="{{ $value['id'] }}">{{ $value['title'] }}</option>
                                    @foreach ($value['children'] as $sub1)
                                    <option value="{{ $sub1['id'] }}">- {{ $sub1['title'] }}</option>
                                    @endforeach
                                    @endforeach

                                </select>
                            </div>


                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/admin/maker/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 1200.88px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Makers</h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'Makers',
                    ]])
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->

    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <form method="POST" action="{{ route('admin.makers.store') }}">
                    <div class="card">

                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" class="form-control">

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>


                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Add New</button>
                        </div>


                    </div>
                </form>
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-name"></h3>

                        <div class="card-tools float-left">
                            <div class="input-group input-group-sm">
                                <input type="text" id="ajax-search" class="form-control" placeholder="Search keywords">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table class="table table-hover table-striped" id="table-ajax">
                                <thead>
                                    <tr role="row">

                                        <th>Name</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($makers as $data)
                                    <tr role="row" class="odd">
                                        <td>{{ $data['name'] }}</td>
                                        <td width=200>
                                            <form onsubmit="return confirm('Please confirm you want to delete!');" action="{{ route('admin.makers.destroy',$data['id']) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <a class="btn btn-sm btn-success" href="{{ route('admin.makers.edit',$data['id'])}}">Update</a>
                                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>

                                    @endforeach
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
@endsection
@section('script')

<script>


</script>
@stop

resources/views/admin/maker/trash.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 1200.88px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Categories <small>(Trash)</small></h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'Categories'=>route('admin.categories.index'),
                    'Trash'
                    ]])
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-4">

                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div id="categories">
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                                        <thead>
                                            <tr role="row">
                                                <th>Title</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($categories as $category)
                                            <tr role="row" class="odd">
                                                <td>{{ $category['title'] }}</td>
                                                <td width=200>
                                                    <a class="btn btn-sm btn-success" href="{{ route('admin.categories.rolback',$category['id']) }}">Rolback</a>
                                                    <a class="btn btn-sm btn-danger" href="{{ route('admin.categories.destroy',$category['id']) }}">Delete</a>
                                                </td>
                                            </tr>
                                    
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
@endsection

resources/views/admin/maker/update.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 1200.88px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Update #{{ $maker->id }}</h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'makers' =>route('admin.makers.index'),
                    'Update #'.$maker->id,
                    ]])
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-4">
                <div class="card">
                    <!-- form start -->
                    <form method="POST" action="{{ route('admin.makers.update',$maker->id) }}">
                        @csrf
                        {{ method_field('PATCH') }}
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $maker->name }}" class="form-control">

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>



                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection