routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'Front\HomeController@index');
Route::get('test', 'Front\HomeController@resize');
Route::get('image/{path}', function ($path) {
    return $path;
});
Route::get('/s/{code}', 'Front\ProductController@getLink');
Route::get('/home', 'Front\HomeController@index')->name('home');
Route::post('/forgot', 'Api\ForgotPasswordController@index')->name('forgot');
Route::post('/updatePassword', 'Api\ForgotPasswordController@updatePassword')->name('updatePassword');
Route::get('p/{slug}-{id}', 'Front\PageController@view')
    ->where('slug', '.*?')
    ->where('id', '\d+');
Route::get('a/{slug}-{id}', 'Front\PageController@viewAfl')
    ->where('slug', '.*?')
    ->where('id', '\d+');
Route::get('f/{code}', 'Front\PageController@getLink');
Route::get('{slug}-{id}', 'Front\ProductController@detail')
    ->where('slug', '.*?')
    ->where('id', '\d+');

Route::get('/filter', 'Front\ProductController@filter');
Route::get('/category/{slug}', 'Front\ProductController@category');
Route::post('/cart/add', 'Front\CartController@add');
Route::post('/cart/update', 'Front\CartController@update');
Route::get('/cart/checkout', 'Front\CartController@checkout')->name('checkout');
Route::post('/cart/remove', 'Front\CartController@remove');
Route::post('/cart/order', 'Front\CartController@order')->name('order');
Route::get('/order/success', 'Front\CartController@success')->name('order.success');
Route::get('/thong-tin-tai-khoan', 'Front\UserController@me')->name('me');
Route::patch('/me/update', 'Front\UserController@update')->name('me.update');

Route::get('/admin', 'Admin\DashboardController@index');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/filemanager/upload', '\Unisharp\Laravelfilemanager\Controllers\UploadController@upload');
});
Route::group(['middleware' => 'is.admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::get('categories/trash', 'Admin\CategoryController@listTrash')->name('categories.trash.list');
    Route::get('categories/rolback/{id}', 'Admin\CategoryController@rolback')->name('categories.rolback');
    Route::get('categories/trash/{id}', 'Admin\CategoryController@trash')->name('categories.trash.delete');
    Route::resource('categories', 'Admin\CategoryController');
    Route::get('articles/trash', 'Admin\ArticleController@listTrash')->name('articles.trash.list');
    Route::get('articles/rolback/{id}', 'Admin\ArticleController@rolback')->name('articles.rolback');
    Route::get('articles/trash/{id}', 'Admin\ArticleController@trash')->name('articles.trash.delete');
    Route::resource('articles', 'Admin\ArticleController');
    Route::get('users/trash', 'Admin\UserController@trash')->name('users.trash');
    Route::get('users/trash/{id}', 'Admin\UserController@trash_destroy')->name('users.trash.delete');
    Route::get('users/me', 'Admin\UserController@me')->name('users.me');
    Route::resource('users', 'Admin\UserController');
    Route::resource('menus', 'Admin\MenuController');
    Route::post('menus/order', 'Admin\MenuController@order')->name('menus.order');
    Route::post('menus/actions', 'Admin\MenuController@actions')->name('menus.actions');
    Route::get('orders/invoice/{order_id}', 'Admin\OrderController@invoice')->name('orders.invoice');
    Route::resource('orders', 'Admin\OrderController');
    Route::post('/ajax/upload', 'Admin\AjaxController@upload');
    Route::resource('settings', 'Admin\SettingController');
    Route::resource('contacts', 'Admin\ContactController');
    Route::get('pages/trash', 'Admin\PageController@listTrash')->name('pages.trash.list');
    Route::get('pages/rolback/{id}', 'Admin\PageController@rolback')->name('pages.rolback');
    Route::get('pages/trash/{id}', 'Admin\PageController@trash')->name('pages.trash.delete');
    Route::resource('pages', 'Admin\PageController');
    Route::get('affs/trash', 'Admin\AffController@listTrash')->name('affs.trash.list');
    Route::get('affs/rolback/{id}', 'Admin\AffController@rolback')->name('affs.rolback');
    Route::get('affs/trash/{id}', 'Admin\AffController@trash')->name('affs.trash.delete');
    Route::resource('affs', 'Admin\AffController');
    Route::resource('widgets', 'Admin\WidgetController');
    Route::post('widgets/actions', 'Admin\WidgetController@actions')->name('widgets.actions');
    Route::resource('makers', 'Admin\MakerController');
    Route::post('makers/actions', 'Admin\MakerController@actions')->name('makers.actions');
});

app/Models/Widget.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Widget extends Model
{
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'prefix', 'name'
    ];
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at'];
    
    public function items()
    {
        return $this->hasMany('App\Models\WidgetItem', 'widget_id', 'id')->select(
            'post_id as id',
            'widget_id',
            'title',
            'slug',
            'image',
            'price',
            'price_sale',
            \DB::raw('(CASE WHEN posts.type = "widget" THEN posts.content ELSE "" END) AS content')
        )->leftjoin('posts', function ($q) {
            $q->on('posts.id', 'widget_items.post_id');
        });
    }
}

app/Http/Controllers/Admin/WidgetController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\WidgetRepository;
use App\Repositories\WidgetItemRepository;
use App\Repositories\UserRepository;
use App\Repositories\CategoryRepository;
use App\Repositories\PageRepository;

class WidgetController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(
        WidgetRepository $widgetRepository,
        WidgetItemRepository $widgetItemRepository,
        UserRepository $userRepository,
        CategoryRepository $categoryRepository,
        PageRepository $pageRepository
    ) {
        $this->middleware('auth');
        $this->_widgetRepository = $widgetRepository;
        $this->_widgetItemRepository = $widgetItemRepository;
        $this->_userRepository = $userRepository;
        $this->_categoryRepository = $categoryRepository;
        $this->_pageRepository = $pageRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $this->_widgetItemRepository->storage();
            $getwidget = $this->_widgetRepository->list();
            $query = null;
            $findWidget = null;
            if ($getwidget) {
                $query = $this->_widgetItemRepository->list($request->widget_id ? $request->widget_id : $getwidget[0]['id']);
                $findWidget = $getwidget[array_search($request->widget_id ? $request->widget_id : $getwidget[0]['id'], array_column($getwidget, 'id'))];
            }

            $category = $this->_categoryRepository->getParent();
            $page = $this->_pageRepository->toArray();
            return view('admin.widget.index', ['widgets' => $query, 'getwidget' => $getwidget, 'category' => $category, 'page' => $page, 'findWidget' => $findWidget]);
        } catch (Exception $e) {
            throw $e;
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            return view('admin.widget.create');
        } catch (Exception $e) {
            throw $e;
        }
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        try {
            $v = [];
            $data = [];

            if ($request->submit == "add") {
                $this->validate($request, array_merge($v, [
                    'prefix' => ['required'],
                    'name' => ['required']
                ]));
                $widget = $this->_widgetRepository->create([
                    'prefix' => $request->prefix,
                    'name' => $request->name,
                    'type' => $request->type
                ]);
            } else {
                $widget = $this->_widgetRepository->find($request->widget_id);
            }
            $post_id = array_pluck($this->_widgetItemRepository->getPostByWidget($request->widget_id), 'post_id');
            if ($request->type == config('global.widget_type.category')) {
                $this->validate($request, array_merge($v, [
                    'category_id' => ['required']
                ]));
                if ($request->post_limit > 0) {
                    foreach ($this->_categoryRepository->getPostInCategory($request->category_id, $request->post_limit) as $post) {
                        if (!in_array($post_id['post_id'], $post_id)) {
                            $this->_widgetItemRepository->create([
                                'widget_id' => $widget->id,
                                'post_id' => $post['post_id']
                            ]);
                        }
                    }
                }
            } elseif ($request->type == config('global.widget_type.html_text')) {
                $this->validate($request, array_merge($v, [
                    'content' => ['required'],
                ]));
                $post = $this->_widgetRepository->createPost([
                    'title' => $widget->name,
                    'slug' => $widget->prefix,
                    'content' => $request->content,
                    'type' => 'widget',
                    'user_id' => \Auth::user()->id,
                    'status' => config('global.status.active')
                ]);
                $this->_widgetItemRepository->create([
                    'widget_id' => $widget->id,
                    'post_id' => $post->id
                ]);
            } else {
                $this->validate($request, array_merge($v, [
                    'page_id' => ['required']
                ]));
                foreach ($request->page_id as $id) {
                    if (!in_array($id, $post_id)) {
                        $this->_widgetItemRepository->create([
                            'widget_id' => $widget->id,
                            'post_id' => $id
                        ]);
                    }
                }
            }
            $this->_widgetItemRepository->storage();
            return redirect()->route('admin.widgets.index', ['widget_id' => $widget->id]);
        } catch (Exception $e) {
            throw $e;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        try {
            $result = $this->_widgetItemRepository->find($id);
            return view('admin.widget.update', ['widget' => $result]);
        } catch (Exception $e) {
            throw $e;
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->validate($request, [
                'title' => ['required', 'string', 'max:255'],
            ]);
            $result = $this->_widgetItemRepository->find($id);
            $this->_widgetItemRepository->update($result->post_id, $request);
            return redirect()->route('admin.widgets.index', ['widget_id' => $result->widget_id]);
        } catch (Exception $e) {
            throw $e;
        }
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $result = $this->_widgetItemRepository->find($id);
            $this->_widgetItemRepository->delete($id);
            return redirect()->route('admin.widgets.index', ['widget_id' => $result['widget_id']])->with('success', 'You have successfully delete!');
        } catch (Exception $e) {
            throw $e;
        }
    }
    public function actions(Request $request)
    {
        if ($request->submit == "apply") {
            return redirect()->route('admin.widgets.index', ['widget_id' => $request->widget_id]);
        } else {
            $this->_widgetRepository->delete($request->widget_id);
            $this->_widgetItemRepository->storage();
            return redirect()->route('admin.widgets.index');
        }
    }
}

resources/views/admin/widget/_item.blade.php
<tr role="row" class="odd">

    <td>{{ $data['title'] }}</td>
    <td>{{ $data['type'] }}</td>
    <td width=200>

        <form onsubmit="return confirm('Please confirm you want to delete!');" action="{{ route('admin.widgets.destroy',$data['id']) }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
            @if($data['type']=='page')
            <a class="btn btn-sm btn-success" href="{{ route('admin.pages.edit',$data['post_id'])}}">Update</a>
            @elseif($data['type']=="article")
            <a class="btn btn-sm btn-success" href="{{ route('admin.articles.edit',$data['post_id'])}}">Update</a>
            @else
            <a class="btn btn-sm btn-success" href="{{ route('admin.widgets.edit',$data['id'])}}">Update</a>
            @endif

            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
        </form>
    </td>
</tr>

resources/views/admin/widget/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 1200.88px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add New</h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'Categories' =>route('admin.categories.index'),
                    'Add New',
                    ]])
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-4">
                <div class="card">
                    <!-- form start -->
                    <form method="POST" action="{{ route('admin.menus.store') }}">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="type">Type</label>
                                <select name="type" class="form-control">
                                    <option value="{{ config('global.menu.key.header') }}">Header</option>
                                    <option value="{{ config('global.menu.key.footer') }}">Footer</option>
                                    <option value="{{ config('global.menu.key.category') }}">Category</option>
                                    <option value="{{ config('global.menu.key.body') }}">Body</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" class="form-control">

                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="link">Link</label>
                                <input id="link" type="text" class="form-control @error('link') is-invalid @enderror" name="link" value="{{ old('link') }}" class="form-control">

                                @error('link')
                                <span class="invalid-feedback" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="parent_id">Parent</label>
                                <select name="parent_id" class="form-control">
                                    <option value="">Choose parent</option>
                                    @foreach ($parents as $value)
                                    <option value="{{ $value['id'] }}">{{ $value['title'] }}</option>
                                    @foreach ($value['children'] as $sub1)
                                    <option value="{{ $sub1['id'] }}">- {{ $sub1['title'] }}</option>
                                    @endforeach
                                    @endforeach

                                </select>
                            </div>


                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/admin/widget/update.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content-wrapper" style="min-height: 1200.88px;">
    <!-- Content Header (widget header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Update #{{ $widget->id }}</h1>
                </div>
                <div class="col-sm-6">
                    @include('admin.includes.breadcrumb', ['breadcrumbs' => [
                    'Widgets' =>route('admin.widgets.index'),
                    'Update #'.$widget->id,
                    ]])
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <form method="POST" action="{{ route('admin.widgets.update',$widget->id) }}" class="form-horizontal" enctype="multipart/form-data">
            @csrf
            {{ method_field('PUT') }}
            <div class="row">
                <div class="col-9">
                    <div class="card">
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="title" class="col-sm-2">Title</label>
                                <div class="col-sm-10">
                                    <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $widget->title }}" class="form-control">

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        {{ $message }}
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="content" class="col-sm-2">Content</label>
                                <div class="col-sm-10">
                                    <textarea id="my-editor" name="content" class="form-control" row=200>{{ $widget->content }}</textarea>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
                <div class="col-3">
                    <div class="card">
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="status" class="col-sm-3">Status</label>
                                <div class="col-sm-9">
                                    <select name="status" class="form-control">
                                        <option value="{{ config('global.status.active') }}" {{ config('global.status.active')==$widget->status?"selected":"" }}>Active </option>
                                        <option value="{{ config('global.status.inactive') }}" {{ config('global.status.inactive')==$widget->status?"selected":"" }}>InActive</option>
                                        <option value="{{ config('global.status.close') }}" {{ config('global.status.close')==$widget->status?"selected":"" }}>Close</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>

                    </div>
                </div>
            </div>
        </form>
    </section>
</div>
@endsection

@section('script')


<script type="text/javascript" src={{ asset('js/upload.js') }}></script>
@stop