routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'Front\HomeController@index');
Route::get('test', 'Front\HomeController@resize');
Route::get('image/{path}', function ($path) {
    return $path;
});
Route::get('/s/{code}', 'Front\ProductController@getLink');
Route::get('/home', 'Front\HomeController@index')->name('home');
Route::post('/forgot', 'Api\ForgotPasswordController@index')->name('forgot');
Route::post('/updatePassword', 'Api\ForgotPasswordController@updatePassword')->name('updatePassword');
Route::get('p/{slug}-{id}', 'Front\PageController@view')
    ->where('slug', '.*?')
    ->where('id', '\d+');
Route::get('a/{slug}-{id}', 'Front\PageController@viewAfl')
    ->where('slug', '.*?')
    ->where('id', '\d+');
Route::get('f/{code}', 'Front\PageController@getLink');
Route::get('{slug}-{id}', 'Front\ProductController@detail')
    ->where('slug', '.*?')
    ->where('id', '\d+');

Route::get('/filter', 'Front\ProductController@filter');
Route::get('/category/{slug}', 'Front\ProductController@category');
Route::post('/cart/add', 'Front\CartController@add');
Route::post('/cart/update', 'Front\CartController@update');
Route::get('/cart/checkout', 'Front\CartController@checkout')->name('checkout');
Route::post('/cart/remove', 'Front\CartController@remove');
Route::post('/cart/order', 'Front\CartController@order')->name('order');
Route::get('/order/success', 'Front\CartController@success')->name('order.success');
Route::get('/thong-tin-tai-khoan', 'Front\UserController@me')->name('me');
Route::patch('/me/update', 'Front\UserController@update')->name('me.update');

Route::get('/admin', 'Admin\DashboardController@index');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/filemanager/upload', '\Unisharp\Laravelfilemanager\Controllers\UploadController@upload');
});
Route::group(['middleware' => 'is.admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::get('categories/trash', 'Admin\CategoryController@listTrash')->name('categories.trash.list');
    Route::get('categories/rolback/{id}', 'Admin\CategoryController@rolback')->name('categories.rolback');
    Route::get('categories/trash/{id}', 'Admin\CategoryController@trash')->name('categories.trash.delete');
    Route::resource('categories', 'Admin\CategoryController');
    Route::get('articles/trash', 'Admin\ArticleController@listTrash')->name('articles.trash.list');
    Route::get('articles/rolback/{id}', 'Admin\ArticleController@rolback')->name('articles.rolback');
    Route::get('articles/trash/{id}', 'Admin\ArticleController@trash')->name('articles.trash.delete');
    Route::resource('articles', 'Admin\ArticleController');
    Route::get('users/trash', 'Admin\UserController@trash')->name('users.trash');
    Route::get('users/trash/{id}', 'Admin\UserController@trash_destroy')->name('users.trash.delete');
    Route::get('users/me', 'Admin\UserController@me')->name('users.me');
    Route::resource('users', 'Admin\UserController');
    Route::resource('menus', 'Admin\MenuController');
    Route::post('menus/order', 'Admin\MenuController@order')->name('menus.order');
    Route::post('menus/actions', 'Admin\MenuController@actions')->name('menus.actions');
    Route::get('orders/invoice/{order_id}', 'Admin\OrderController@invoice')->name('orders.invoice');
    Route::resource('orders', 'Admin\OrderController');
    Route::post('/ajax/upload', 'Admin\AjaxController@upload');
    Route::resource('settings', 'Admin\SettingController');
    Route::resource('contacts', 'Admin\ContactController');
    Route::get('pages/trash', 'Admin\PageController@listTrash')->name('pages.trash.list');
    Route::get('pages/rolback/{id}', 'Admin\PageController@rolback')->name('pages.rolback');
    Route::get('pages/trash/{id}', 'Admin\PageController@trash')->name('pages.trash.delete');
    Route::resource('pages', 'Admin\PageController');
    Route::get('affs/trash', 'Admin\AffController@listTrash')->name('affs.trash.list');
    Route::get('affs/rolback/{id}', 'Admin\AffController@rolback')->name('affs.rolback');
    Route::get('affs/trash/{id}', 'Admin\AffController@trash')->name('affs.trash.delete');
    Route::resource('affs', 'Admin\AffController');
    Route::resource('widgets', 'Admin\WidgetController');
    Route::post('widgets/actions', 'Admin\WidgetController@actions')->name('widgets.actions');
    Route::resource('makers', 'Admin\MakerController');
    Route::post('makers/actions', 'Admin\MakerController@actions')->name('makers.actions');
});

resources/views/admin/includes/alert.blade.php
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    {{ session()->get('success') }}
</div>
@endif

resources/views/admin/includes/breadcrumb.blade.php
@if (! empty($breadcrumbs))
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
    @foreach ($breadcrumbs as $label => $link)
    @if (is_int($label) && ! is_int($link))
    <li class="breadcrumb-item active">{{ $link }}</li>
    @else
    <li class="breadcrumb-item"><a href="{{ $link }}">{{ $label }}</a></li>
    @endif
    @endforeach
</ol>
@endif

resources/views/admin/includes/header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>

    </ul>



    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item">
            <a class="nav-link" data-toggle="dropdown" href="#">
                {{Auth::user()->name}} <i class="fas fa-th-large"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right">

                <a href="{{ route('admin.users.me') }}" class="dropdown-item">Change profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                                                                             document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/admin/includes/sidebar.blade.php
<!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">

        <div class="info">
            <a href="#" class="d-block">{{ Auth::user()->name }}</a>

        </div>
    </div>
    @php
    $path = explode('/',Request::path());
    $name=!empty($path[1])?$path[1]:$path[0];
    $action=!empty($path[2])?$path[2]:null;
    @endphp
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                       with font-awesome or any other icon font library -->
            <li class="nav-item {{ $name==='dashboard'?'menu-open':"" }}">
                <a href=" {{ route('admin.dashboard') }}" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        Dashboard
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>

            </li>
            <li class="nav-item {{ $name==='categories'?'menu-open':"" }}">
                <a href="{{ route('admin.categories.index') }}" class="nav-link ">
                    <i class="nav-icon fas fa-list-alt "></i>
                    <p>
                        Danh mục
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav">
                    <li class="nav-item">
                        <a href="{{ route('admin.categories.create') }}" class="nav-link {{ ($name==='categories' && $action=='create')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thêm mới</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('admin.categories.trash.list') }}" class="nav-link {{ ($name==='categories' && $action=='trash')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thùng rác</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item {{ $name==='makers'?'menu-open':"" }}">
                <a href="{{ route('admin.makers.index') }}" class="nav-link ">
                    <i class="nav-icon fas fa-list-alt "></i>
                    <p>
                        Hãng sản xuất
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav">
                    <li class="nav-item">
                        <a href="{{ route('admin.makers.create') }}" class="nav-link {{ ($name==='makers' && $action=='create')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thêm mới</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item {{ $name==='articles'?'menu-open':"" }}">
                <a href="{{ route('admin.articles.index') }}" class="nav-link ">
                    <i class="nav-icon fas fa-newspaper"></i>
                    <p>
                        Sản phẩm
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav">
                    <li class="nav-item">
                        <a href="{{ route('admin.articles.create') }}" class="nav-link {{ ($name==='articles' && $action=='create')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thêm mới</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{{ route('admin.articles.trash.list') }}" class="nav-link {{ ($name==='articles' && $action=='trash')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thùng rác</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item {{ $name==='affs'?'menu-open':"" }}">
                <a href="{{ route('admin.affs.index') }}" class="nav-link ">
                    <i class="nav-icon fas fa-newspaper"></i>
                    <p>
                        Aff
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav">
                    <li class="nav-item">
                        <a href="{{ route('admin.affs.create') }}" class="nav-link {{ ($name==='affs' && $action=='create')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thêm mới</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{{ route('admin.affs.trash.list') }}" class="nav-link {{ ($name==='affs' && $action=='trash')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thùng rác</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item {{ $name==='lfm'?'menu-open':"" }}">
                <a target="_blank" href="/filemanager?type=images" class="nav-link">
                    <i class="fas fa-image nav-icon"></i>
                    <p>Hình ảnh</p>
                </a>
            </li>
            <li class="nav-item {{ $name==='orders'?'menu-open':"" }}">
                <a href="{{ route('admin.orders.index') }}" class="nav-link">
                    <i class="fas fa-phone nav-icon"></i>
                    <p>Đơn hàng</p>
                </a>
            </li>
            <li class="nav-item {{ $name==='pages'?'menu-open':"" }}">
                <a href="{{ route('admin.pages.index') }}" class="nav-link ">
                    <i class="nav-icon fas fa-newspaper"></i>
                    <p>
                        Trang
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav">
                    <li class="nav-item">
                        <a href="{{ route('admin.pages.create') }}" class="nav-link {{ ($name==='pages' && $action=='create')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thêm mới</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{{ route('admin.pages.trash.list') }}" class="nav-link {{ ($name==='pages' && $action=='trash')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thùng rác</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item {{ $name==='menus'?'menu-open':"" }}">
                <a href="{{ route('admin.menus.index') }}" class="nav-link ">
                    <i class="nav-icon fas fa-list-alt "></i>
                    <p>
                        Menus
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
            </li>
            <li class="nav-item {{ $name==='widgets'?'menu-open':"" }}">
                <a href="{{ route('admin.widgets.index') }}" class="nav-link ">
                    <i class="nav-icon fas fa-list-alt "></i>
                    <p>
                        Widgets
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
            </li>

            <li class="nav-item {{ $name==='users'?'menu-open':"" }}">
                <a href=" {{ route('admin.users.index') }}" class="nav-link ">
                    <i class="nav-icon fas fa-users"></i>
                    <p>
                        Thành viên
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav">

                    <li class="nav-item">
                        <a href="{{ route('admin.users.create') }}" class="nav-link {{ ($name==='users' && $action=='create')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thêm mới</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('admin.users.trash') }}" class="nav-link {{ ($name==='users' && $action=='trash')?'active':"" }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thùng rác</p>
                        </a>
                    </li>

                </ul>
            </li>
            <li class="nav-item {{ $name==='contacts'?'menu-open':"" }}">
                <a href="{{ route('admin.contacts.index') }}" class="nav-link">
                    <i class="fas fa-phone nav-icon"></i>
                    <p>Liên hệ</p>
                </a>
            </li>
            <li class="nav-item {{ $name==='settings'?'menu-open':"" }}">
                <a href="{{ route('admin.settings.index') }}" class="nav-link">
                    <i class="fas fa-cog nav-icon"></i>
                    <p>Cấu hình</p>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>
<!-- /.sidebar -->